version: "2"

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"
  commands:
    - echo "Using pre-built documentation from prebuilt-docs/html"
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r prebuilt-docs/html/* $READTHEDOCS_OUTPUT/html/
    - echo "Pre-built documentation copied successfully"
