version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    # Install requirements
    - pip install -r requirements.txt
    # Build the documentation with the correct output directory
    - sphinx-build -b html . $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

formats:
  - epub
